apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-gateway-server
  namespace: order-dev
data:
  CONFIG_SERVER_URL: http://config-server.order-dev.svc.cluster.local
  EUREKA_SERVER_URL: http://eureka-server.order-dev.svc.cluster.local/eureka/