apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: order-system-ingress
  namespace: order-dev
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: order-dev.example
      http:
        paths:
          - path: /order(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: gateway-server
                port:
                  number: 80