name: Build and Push Microservices

on:
  push:
    branches:
      - main

jobs:

  # JOB 1 : Build Maven une seule fois
  build-maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install all Maven modules
        run: mvn -B -DskipTests install

      - name: Upload JARs 
        uses: actions/upload-artifact@v4
        with: 
         name: jars 
         path: '**/target/*.jar'
    
    outputs:
      maven_done: "true"

  # JOB 2 : Build Docker par microservice (matrix)
  build-docker:
    needs: build-maven   # d√©pend du job Maven
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - eureka-server
          - config-server
          - gateway-server
          - infra-order
          - infra-inventory
          - infra-notification

    steps:
      - uses: actions/checkout@v3
        
      - name: Download JARs 
        uses: actions/download-artifact@v4
        with: 
         name: jars  #nom de dossier

      - name: Check if this service changed
        id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            changed:
              - '${{ matrix.service }}/**'
              - 'frontend/**'

      - name: Skip if no changes
        if: steps.changes.outputs.changed != 'true'
        run: echo "No changes for ${{ matrix.service }}"

      - name: Login to Docker Hub
        if: steps.changes.outputs.changed == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        if: steps.changes.outputs.changed == 'true'
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest \
            ./${{ matrix.service }}

      - name: Push image
        if: steps.changes.outputs.changed == 'true'
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest
